### ISSUE TITLE
Create an initial design for AR markers

### ISSUE THREAD

**Issue by Piumal1999** [cepdnaclk/e18-co227-Augmented-Reality-Guidance-System#6]
In this project, we'll be printing markers and pasting those in front of each lab/room to support AR image tracking. For the markers, we need a good design which should be simple and easily trackable by AR.js. 

- [x] Create an initial design for the marker(as a rough sketch)

**Comment by Konara98** [comment]
We created two initial designs for AR markers. 
1.This design was created for HOD's Office. It will display the room Id ,name of the office, floor number and Owner of office.
![Design of HOD's office](https://user-images.githubusercontent.com/97779686/174491237-21701a9e-419b-48be-928b-f3ff61793090.png)
2.This design was created for networking laboratory. It will display the room Id ,name of the laboratory, floor number, person in charge, features, list of working staff and additional notes.
![Design of Networking laboratory](https://user-images.githubusercontent.com/97779686/174491763-18d31111-825e-458b-8865-7916fe75be14.png)

**Comment by Piumal1999** [comment]
There were some problem with the initial design. 
1. For better marker tracking, we should use only black and white trackers
2. And the markers should have clearly visible differences
3. ARjs latest version only supports only square-shaped trackers. (It's possible to encode custom-shaped tracker images, but ARjs doesn't track them )

So we created a new design.

- This is the design for room trackers. It contains the room id
<img width="465" alt="image" src="https://user-images.githubusercontent.com/27498587/176029581-d73c9723-4161-44b6-bb4c-403df6d87906.png">

- This is the design for floor trackers. It contains the floor id (F-0, F-1, F-2....)
<img width="465" alt="image" src="https://user-images.githubusercontent.com/27498587/176029890-44ca267f-aeff-45c0-8d3a-0a459101d729.png">
