### ISSUE TITLE
Create a design for the AR Overlay content

### ISSUE THREAD

**Issue by Piumal1999** [cepdnaclk/e18-co227-Augmented-Reality-Guidance-System#9]
**Requirement**
When the AR camera detects a selected room/floor tracker, it should display the details of the room/floor in an Augmented Reality overlay. We need to create a design for this overlay.

**Expected outcome**
A rough sketch for the design of AR overlay content

**Comment by Piumal1999** [comment]
Created few sample ar displays:

1. Rooms
![trackers-06](https://user-images.githubusercontent.com/27498587/176045773-b8df6bf6-9615-4334-a199-1d11b92b55f9.png)

2. Floors
![trackers-07](https://user-images.githubusercontent.com/27498587/176045779-9f1d96bf-775a-45fb-bd1d-851bd5fc12b6.png)

**Comment by chathurawimalasiri** [comment]
This one is good.
